server:
    port: ${PORT:8090}

spring:
    application:
        name: weekly-achievements-gateway-service

logging:
    level:
        org.springframework.cloud.netflix.zuul: TRACE

zuul:
    routes:
        weekly-achievements-core-service:
            path: /wacs/**
            sensitiveHeaders:
            serviceId: weekly-achievements-core-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8273/eureka/